import { AppConstants, apiUrl, apiTenantUrl, baseHeader, multipartFormHeader, bookingUrl } from '.';

const apiConfig = {
    account: {
        login: {
            baseURL: `${apiUrl}v1/account/login`,
            method: 'POST',
            headers: baseHeader,
        },
        loginBasic: {
            baseURL: `${apiUrl}api/token`,
            method: 'POST',
            headers: baseHeader,
        },
        getProfile: {
            baseURL: `${apiUrl}v1/account/profile`,
            method: 'GET',
            headers: baseHeader,
        },
        updateProfile: {
            baseURL: `${apiUrl}v1/account/update_profile_admin`,
            method: 'PUT',
            headers: baseHeader,
        },
        getById: {
            baseURL: `${apiUrl}v1/account/get/:id`,
            method: 'GET',
            headers: baseHeader,
        },
        refreshToken: {
            baseURL: `${apiUrl}v1/account/refresh_token`,
            method: 'POST',
            headers: baseHeader,
        },
        logout: {
            baseURL: `${apiUrl}v1/account/logout`,
            method: 'GET',
            headers: baseHeader,
        },
    },
    user: {
        getList: {
            baseURL: `${apiUrl}v1/account/list`,
            method: `GET`,
            headers: baseHeader,
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/account/auto-complete`,
            method: `GET`,
            headers: baseHeader,
        },
        getById: {
            baseURL: `${apiUrl}v1/account/get/:id`,
            method: `GET`,
            headers: baseHeader,
        },
        create: {
            baseURL: `${apiUrl}v1/account/create_admin`,
            method: `POST`,
            headers: baseHeader,
        },
        update: {
            baseURL: `${apiUrl}v1/account/update_admin`,
            method: `PUT`,
            headers: baseHeader,
        },
        delete: {
            baseURL: `${apiUrl}v1/account/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
        },
    },
    file: {
        upload: {
            path: `${AppConstants.mediaRootUrl}v1/file/upload`,
            method: 'POST',
            headers: multipartFormHeader,
            //isRequiredTenantId: true,
            isUpload: true,
        },
    },
    category: {
        getList: {
            baseURL: `${apiTenantUrl}v1/category/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${apiTenantUrl}v1/category/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${apiTenantUrl}v1/category/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${apiTenantUrl}v1/category/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${apiTenantUrl}v1/category/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${apiTenantUrl}v1/category/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    organize: {
        getList: {
            baseURL: `${apiUrl}v1/service/list`,
            method: `GET`,
            headers: baseHeader,
        },
        getById: {
            baseURL: `${apiUrl}v1/service/get/:id`,
            method: `GET`,
            headers: baseHeader,
        },
        getDetail: {
            baseURL: `${apiUrl}v1/service/detail/:id`,
            method: `GET`,
            headers: baseHeader,
        },
        create: {
            baseURL: `${apiUrl}v1/service/create`,
            method: `POST`,
            headers: baseHeader,
        },
        update: {
            baseURL: `${apiUrl}v1/service/update`,
            method: `PUT`,
            headers: baseHeader,
        },
        delete: {
            baseURL: `${apiUrl}v1/service/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
        },
        getProfile: {
            baseURL: `${apiUrl}v1/service/profile`,
            method: 'GET',
            headers: baseHeader,
        },
        updateProfile: {
            baseURL: `${apiUrl}v1/service/update_profile`,
            method: 'PUT',
            headers: baseHeader,
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/service/auto-complete`,
            method: `GET`,
            headers: baseHeader,
        },
    },

    driver: {
        getList: {
            baseURL: `${bookingUrl}/v1/driver/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/driver/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/driver/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/driver/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/driver/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/driver/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        dashboardTopDriver: {
            baseURL: `${bookingUrl}/v1/driver/dashboard-top-driver`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        listActivityRate: {
            baseURL: `${bookingUrl}/v1/driver/list-activity-rate`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    driverService: {
        getList: {
            baseURL: `${bookingUrl}/v1/driver-service/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/driver-service/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/driver-service/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/driver-service/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/driver-service/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/driver-service/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    nation: {
        getList: {
            baseURL: `${bookingUrl}/v1/nation/list`,
            method: `GET`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/nation/auto-complete`,
            method: `GET`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/nation/get/:id`,
            method: `GET`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/nation/create`,
            method: `POST`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/nation/update`,
            method: `PUT`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/nation/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    service: {
        getList: {
            baseURL: `${bookingUrl}/v1/user-service/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/user-service/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/user-service/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/user-service/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/user-service/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/user-service/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    driverVehicle: {
        getList: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getByDriver: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/get-driver-vehicle/:driverId`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/driver-vehicle/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    position: {
        getList: {
            baseURL: `${bookingUrl}/v1/position/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/position/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/position/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/position/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/position/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/position/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    customer: {
        getList: {
            baseURL: `${bookingUrl}/v1/customer/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/customer/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/customer/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/customer/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/customer/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/customer/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    booking: {
        getList: {
            baseURL: `${bookingUrl}/v1/booking/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/booking/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/booking/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/booking/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        updateState: {
            baseURL: `${bookingUrl}/v1/booking/update-state`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/booking/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/booking/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        accept: {
            baseURL: `${bookingUrl}/v1/booking/accept`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        cancel: {
            baseURL: `${bookingUrl}/v1/booking/cancel`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        direct: {
            baseURL: `${bookingUrl}/v1/booking/direct`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        revenue: {
            baseURL: `${bookingUrl}/v1/booking/revenue-statistic`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        dashboardSummary: {
            baseURL: `${bookingUrl}/v1/booking/dashboard-summary`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        revenueStatistic: {
            baseURL: `${bookingUrl}/v1/booking/dashboard-revenue-statistic`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        finance: {
            baseURL: `${bookingUrl}/v1/booking/list-finance`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getSumFinance: {
            baseURL: `${bookingUrl}/v1/booking/get-sum-finance`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        exportFinance: {
            baseURL: `${bookingUrl}/v1/booking/export-to-excel-list-finance`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    map: {
        getList: {
            baseURL: `${bookingUrl}/v1/driver/list-online-driver`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    room: {
        getList: {
            baseURL: `${bookingUrl}/v1/room/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/room/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/room/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/room/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/room/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/room/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    chatDetail: {
        getByClient: {
            baseURL: `${bookingUrl}/v1/chat-detail/client-get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getByRoom: {
            baseURL: `${bookingUrl}/v1/chat-detail/my-chat-by-room/:roomId`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        deleteClient: {
            baseURL: `${bookingUrl}/v1/chat-detail/client-delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    promotion: {
        getList: {
            baseURL: `${bookingUrl}/v1/promotion/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/promotion/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/promotion/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/promotion/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/promotion/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/promotion/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    requestPayout: {
        getList: {
            baseURL: `${bookingUrl}/v1/request-pay-out/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/request-pay-out/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/request-pay-out/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        updateState: {
            baseURL: `${bookingUrl}/v1/request-pay-out/update-state`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/request-pay-out/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${bookingUrl}/v1/request-pay-out/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    settings: {
        getList: {
            baseURL: `${apiTenantUrl}v1/settings/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${apiTenantUrl}v1/settings/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${apiTenantUrl}v1/settings/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${apiTenantUrl}v1/settings/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${apiTenantUrl}v1/settings/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        autocomplete: {
            baseURL: `${apiTenantUrl}v1/settings/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    news: {
        getList: {
            baseURL: `${bookingUrl}/v1/news/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${bookingUrl}/v1/news/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${bookingUrl}/v1/news/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        update: {
            baseURL: `${bookingUrl}/v1/news/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        delete: {
            baseURL: `${bookingUrl}/v1/news/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    walletTransaction: {
        getList: {
            baseURL: `${bookingUrl}/v1/wallet-transaction/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        listSum: {
            baseURL: `${bookingUrl}/v1/wallet-transaction/list-sum`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getSum: {
            baseURL: `${bookingUrl}/v1/wallet-transaction/get-sum`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        exportTransaction: {
            baseURL: `${bookingUrl}/v1/wallet-transaction/export-to-excel-list-transaction`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },

    },
};
export default apiConfig;
